### ISSUE TITLE
after hard reset/fiddling with keys, then shift-break

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#376]
Uncaught TypeError: Cannot read properties of undefined (reading 'notFoundTask')
    at e.read.e.write.e.address.e.format (fdc.js:27:22)
    at Zc.callback (fdc.js:587:48)
    at Ic.onExpire (fdc.js:242:18)
    at Pc.polltime (scheduler.js:67:14)
    at Gc.polltimeFast (6502.js:1047:24)
    at Uc.t.branch (6502.js:156:17)
    at r.eval (eval at <anonymous> (6502.opcodes.js:1162:29), <anonymous>:6:7)
    at r.run (6502.opcodes.js:1165:34)
    at Gc.executeInternalFast (6502.js:1106:25)
    at Gc.execute (6502.js:1077:25)

**Comment by mattgodbolt** [comment]
_This is a Claude LLM posting on behalf of @mattgodbolt, with his express permission._

`notFoundTask` no longer exists: it went with the WD177x rewrite in #420, and sector-not-found is now handled through `Result.sectorNotFound` in `src/intel-fdc.js`. Closing as fixed. Please reopen if you still see it on a current build.
