### ISSUE TITLE
1770 HFEs don't work

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#432]
Trying to load Exile's HFE image, it hangs:
![image](https://github.com/user-attachments/assets/d4875e59-f3aa-4030-843d-74b688b3f316)

@richtw1 suggests "not generating an NMI that it's expecting"

Also the 1770 track step sound doesn't work, mayyybe related?

**Comment by richtw1** [comment]
```
event noted: exception thrown Error: Bad state undefined
    at Eu._byteReceived (https://master.xania.org/main.b81413c0ac78024bf6f1.js:2:349560)
    at Eu._bitstreamReceived (https://master.xania.org/main.b81413c0ac78024bf6f1.js:2:347099)
    at Eu._pulsesCallback (https://master.xania.org/main.b81413c0ac78024bf6f1.js:2:341653)
    at Cu.r [as _pulsesCallback] (https://master.xania.org/main.b81413c0ac78024bf6f1.js:2:333234)
    at Cu._onTimer (https://master.xania.org/main.b81413c0ac78024bf6f1.js:2:329045)
    at gl.polltime (https://master.xania.org/main.b81413c0ac78024bf6f1.js:2:264294)
    at Ml.polltimeCommon (https://master.xania.org/main.b81413c0ac78024bf6f1.js:2:302448)
    at Ml.polltimeFast (https://master.xania.org/main.b81413c0ac78024bf6f1.js:2:303097)
    at Ml.branch (https://master.xania.org/main.b81413c0ac78024bf6f1.js:2:288148)
    at n.exec_30_bmi_branch (eval at <anonymous> (https://master.xania.org/main.b81413c0ac78024bf6f1.js:2:242893), <anonymous>:6:7)
```
console output
