### ISSUE TITLE
Accessing FE18 crashes the emulator

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#456]
Reported by email:
```basic
PRINT ?&FE18
```
crashes jsbeeb.

**Comment by mattgodbolt** [comment]
```
Cannot set properties of null (setting 'econetNMIEnabled')
TypeError: Cannot set properties of null (setting 'econetNMIEnabled')
    at Cpu6502.handleEconetStationId (http://localhost:8080/main.js:23833:38)
    at Cpu6502.readDevice (http://localhost:8080/main.js:23893:81)
    at Cpu6502.readmem (http://localhost:8080/main.js:23991:30)
    at Runner.exec_b1_lda_ind_y (eval at generate6502JumpTable (http://localhost:8080/main.js:25771:32), <anonymous>:25:15)
    at Runner.exec [as run] (http://localhost:8080/main.js:25786:34)
    at Cpu6502.executeInternalFast (http://localhost:8080/main.js:24401:25)
    at Cpu6502.execute (http://localhost:8080/main.js:24370:25)
    at draw (http://localhost:8080/main.js:35431:28)
    ```
